namespace: ansible
name: docker
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.windows: '>=1.0'
  ansible.unix: '>=1.0'
  ansible.misc: '>=1.0'
repository: git@github.com:ansible-collection-migration/ansible.docker.git
documentation: https://github.com/ansible-collection-migration/ansible.docker/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.docker
issues: https://github.com/ansible-collection-migration/ansible.docker/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
